server:
  port: 8080
spring:
  application:
    name: shard-upload
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend?rewriteBatchedStatements=true&useUnicode=true&serverTimezone=Asia/Shanghai&autoReconnect=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root123
  sql:
    init:
      schema-locations: classpath:db/table.sql
      mode: always
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
